### ISSUE TITLE
Create stub config files

### ISSUE THREAD

**Issue by oalders** [houseabsolute/precious#53]
As a wishlist item, it would be cool to have `precious config --create` to create a stub config file, maybe including some defaults for various languages.

`precious config --create --lang go --lang bash precious.toml`

I added something like this to `perlimports` and I use it all the time:

`perlimports --create-config-file perlimports.toml`

This is somewhat related to #3

**Comment by autarch** [comment]
I have a first pass at this in the `config-init` branch that handles the following components:

* Go
* Rust
* Perl
* `.gitignore` files
* Markdown
* YAML

If you have any suggestions for config for other languages I can include those too, but I haven't really used `precious` with anything else yet.

**Comment by oalders** [comment]
The branch looks great! I tried it out and I love that it creates `dev/bin/check-go-mod.sh` for you. I would be able to use that right away.

For Perl, I would suggest adding:

```toml
[commands.perlimports]
type = "both"
include = [ "**/*.{pl,pm,t,psgi}" ]
cmd = [ "perlimports" ]
lint_flags = ["--lint" ]
tidy_flags = ["-i" ]
ok_exit_codes = 0
expect_stderr = true
```

It might also be helpful if you could specify a different config file path rather than the default, so that you could create one in your home directory or with a `.precious.toml`. I'm testing this out in the top level of the repo and I had to blow away the original config file to test this. Not a big deal, though. I'd file that under "nice to have".
